name: CI-CD pipeline

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        name: setup, builds
        steps:
            - name: Checkout
              uses: actions/checkout@4

            - name: Setup Node.JS
              uses: actions/setup-node@4
              with:
                node-version: '24'
                cache: 'npm'
            
            - name: Install dependencies
              run: npm ci

            - name: testing application
              run: npm run test
            
            - name: build application
              run: npm run build